server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: microservice-one
          uri: lb://MICROSERVICE-ONE
          predicates:
            - Path=/service-one/**
        - id: microservice-two
          uri: lb://MICROSERVICE-TWO
          predicates:
            - Path=/service-two/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
