server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: microservice-one
          uri: lb://MICROSERVICE-ONE-SERVICE
          predicates:
            - Path=/service-one/**
        - id: microservice-two
          uri: lb://MICROSERVICE-TWO-SERVICE
          predicates:
            - Path=/service-two/**
