server:
  port: 9090

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: microservice-one
          uri: http://localhost:8082
          predicates:
            - Path=/microservice-one/**
        - id: microservice-two
          uri: http://localhost:8083
          predicates:
            - Path=/microservice-two/**
        - id: security-service
          uri: http://localhost:8084
          predicates:
            - Path=/security/**
        - id: logging-service
          uri: http://localhost:8085
          predicates:
            - Path=/logging/**
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
